# Generated by Django 5.0.3 on 2026-03-30 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0002_monthlyschedule_waiterslot_scheduleentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notification_type', models.CharField(choices=[('schedule_published', 'Новое расписание опубликовано'), ('slot_claimed', 'Сотрудник занял позицию'), ('manual_assignment', 'Ручное назначение'), ('assignment_accepted', 'Назначение подтверждено'), ('assignment_rejected', 'Назначение отклонено'), ('schedule_reminder', 'Напоминание о расписании')], db_index=True, max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='Требует подтверждения')),
                ('confirmation_status', models.CharField(choices=[('none', 'Не требуется'), ('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='none', max_length=10, verbose_name='Статус подтверждения')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено в')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('related_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.monthlyschedule', verbose_name='Расписание')),
                ('related_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.waiterslot', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
