# Generated by Django 5.0.3 on 2026-04-03 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('shifts', '0003_waiterslot_employee_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'РЈРІРµРґРѕРјР»РµРЅРёРµ', 'verbose_name_plural': 'РЈРІРµРґРѕРјР»РµРЅРёСЏ'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='confirmation_status',
            field=models.CharField(choices=[('none', 'РќРµ С‚СЂРµР±СѓРµС‚СЃСЏ'), ('pending', 'РћР¶РёРґР°РµС‚ РѕС‚РІРµС‚Р°'), ('accepted', 'РџСЂРёРЅСЏС‚Рѕ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅРѕ')], default='none', max_length=10, verbose_name='РЎС‚Р°С‚СѓСЃ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='РџРѕРґС‚РІРµСЂР¶РґРµРЅРѕ РІ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='РџСЂРѕС‡РёС‚Р°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='РЎРѕРѕР±С‰РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('schedule_published', 'РќРѕРІРѕРµ СЂР°СЃРїРёСЃР°РЅРёРµ РѕРїСѓР±Р»РёРєРѕРІР°РЅРѕ'), ('slot_claimed', 'РЎРѕС‚СЂСѓРґРЅРёРє Р·Р°РЅСЏР» РїРѕР·РёС†РёСЋ'), ('manual_assignment', 'Ручное назначение'), ('assignment_unassigned', 'Назначение отменено'), ('assignment_accepted', 'РќР°Р·РЅР°С‡РµРЅРёРµ РїРѕРґС‚РІРµСЂР¶РґРµРЅРѕ'), ('assignment_rejected', 'РќР°Р·РЅР°С‡РµРЅРёРµ РѕС‚РєР»РѕРЅРµРЅРѕ'), ('schedule_reminder', 'РќР°РїРѕРјРёРЅР°РЅРёРµ Рѕ СЂР°СЃРїРёСЃР°РЅРёРё')], db_index=True, max_length=30, verbose_name='РўРёРї'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СѓС‡Р°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.monthlyschedule', verbose_name='Р\xa0Р°СЃРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.waiterslot', verbose_name='РџРѕР·РёС†РёСЏ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='РўСЂРµР±СѓРµС‚ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє'),
        ),
    ]
