# Generated by Django 5.0.3 on 2026-04-03 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
        ('shifts', '0003_waiterslot_employee_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='confirmation_status',
            field=models.CharField(choices=[('none', 'Не требуется'), ('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='none', max_length=10, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено в'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('schedule_published', 'Новое расписание опубликовано'), ('slot_claimed', 'Сотрудник занял позицию'), ('manual_assignment', 'Ручное назначение'), ('assignment_unassigned', 'Назначение отменено'), ('assignment_accepted', 'Назначение подтверждено'), ('assignment_rejected', 'Назначение отклонено'), ('schedule_reminder', 'Напоминание о расписании')], db_index=True, max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.monthlyschedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.waiterslot', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='Требует подтверждения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
