# Generated by Django 5.0.3 on 2026-03-31 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0002_monthlyschedule_waiterslot_scheduleentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка данных'), ('training', 'Обучение модели'), ('forecasting', 'Генерация прогноза'), ('completed', 'Завершён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=15, verbose_name='Статус')),
                ('process_data', models.BooleanField(default=True, verbose_name='Обработать данные')),
                ('train_model', models.BooleanField(default=True, verbose_name='Обучить модель')),
                ('make_forecast', models.BooleanField(default=True, verbose_name='Сделать прогноз')),
                ('evaluate', models.BooleanField(default=True, verbose_name='Оценить точность')),
                ('forecast_from', models.DateField(blank=True, null=True, verbose_name='Прогноз с')),
                ('forecast_to', models.DateField(blank=True, null=True, verbose_name='Прогноз по')),
                ('hours_ahead', models.PositiveIntegerField(default=720, verbose_name='Часов вперёд')),
                ('accuracy_pct', models.FloatField(blank=True, null=True, verbose_name='Точность %')),
                ('mae', models.FloatField(blank=True, null=True, verbose_name='MAE')),
                ('r2_score', models.FloatField(blank=True, null=True, verbose_name='R²')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='shifts.venue', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Запуск прогноза',
                'verbose_name_plural': 'Запуски прогнозов',
                'db_table': 'forecast_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('hour', models.PositiveSmallIntegerField(verbose_name='Час')),
                ('day_of_week', models.PositiveSmallIntegerField(verbose_name='День недели')),
                ('is_peak_hour', models.BooleanField(default=False, verbose_name='Пиковый час')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='Выходной')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Праздник')),
                ('orders_predicted', models.FloatField(verbose_name='Заказы (прогноз)')),
                ('orders_with_buffer', models.FloatField(verbose_name='Заказы (с буфером)')),
                ('guests_predicted', models.FloatField(verbose_name='Гости (прогноз)')),
                ('guests_with_buffer', models.FloatField(verbose_name='Гости (с буфером)')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='forecasting.forecastrun', verbose_name='Запуск')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='shifts.venue', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Почасовой прогноз',
                'verbose_name_plural': 'Почасовые прогнозы',
                'db_table': 'hourly_forecasts',
                'ordering': ['forecast_datetime'],
                'indexes': [models.Index(fields=['venue', 'date'], name='hourly_fore_venue_i_44e4b2_idx')],
            },
        ),
    ]
