# Generated by Django 5.0.3 on 2026-03-30 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('raw_csv', models.TextField(blank=True, default='', help_text='Сохраняем оригинал для отладки и повторного парсинга', verbose_name='Исходный CSV')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано в')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shifts.venue', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Расписание на месяц',
                'verbose_name_plural': 'Расписания на месяц',
                'db_table': 'monthly_schedules',
                'ordering': ['-year', '-month'],
                'unique_together': {('venue', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WaiterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('waiter_num', models.PositiveIntegerField(verbose_name='Номер официанта')),
                ('assignment_status', models.CharField(choices=[('open', 'Свободно'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено')], default='open', max_length=10, verbose_name='Статус назначения')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Назначен в')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён в')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный сотрудник')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shifts.monthlyschedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Позиция официанта',
                'verbose_name_plural': 'Позиции официантов',
                'db_table': 'waiter_slots',
                'ordering': ['waiter_num'],
                'unique_together': {('schedule', 'waiter_num')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_working', models.BooleanField(default=False, verbose_name='Рабочий день')),
                ('shift_type', models.CharField(choices=[('off', 'Выходной'), ('full', 'Полная'), ('morning', 'Утренняя'), ('evening', 'Вечерняя')], default='off', max_length=10, verbose_name='Тип смены')),
                ('waiters_needed', models.PositiveIntegerField(default=0, help_text='Сколько официантов нужно в этот день (из прогноза)', verbose_name='Требуется официантов')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('work_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Часы')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shifts.waiterslot', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Запись расписания',
                'verbose_name_plural': 'Записи расписания',
                'db_table': 'schedule_entries',
                'ordering': ['date'],
                'unique_together': {('slot', 'date')},
            },
        ),
    ]
