# Generated by Django 5.0.3 on 2026-04-02 13:54

from django.db import migrations, models


def add_employee_level_if_missing(apps, schema_editor):
    table_name = "waiter_slots"
    column_name = "employee_level"

    with schema_editor.connection.cursor() as cursor:
        columns = {
            c.name
            for c in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if column_name in columns:
        return

    WaiterSlot = apps.get_model("shifts", "WaiterSlot")
    field = models.CharField(
        blank=True,
        choices=[
            ("employee_pro", "Опытный"),
            ("employee_noob", "Стажёр"),
        ],
        db_index=True,
        help_text=(
            "Тип официанта из сгенерированного расписания "
            "(employee_pro/employee_noob)"
        ),
        max_length=20,
        null=True,
        verbose_name="Уровень слота",
    )
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(WaiterSlot, field)


def remove_employee_level_if_exists(apps, schema_editor):
    table_name = "waiter_slots"
    column_name = "employee_level"

    with schema_editor.connection.cursor() as cursor:
        columns = {
            c.name
            for c in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if column_name not in columns:
        return

    WaiterSlot = apps.get_model("shifts", "WaiterSlot")
    field = models.CharField(
        blank=True,
        choices=[
            ("employee_pro", "Опытный"),
            ("employee_noob", "Стажёр"),
        ],
        db_index=True,
        help_text=(
            "Тип официанта из сгенерированного расписания "
            "(employee_pro/employee_noob)"
        ),
        max_length=20,
        null=True,
        verbose_name="Уровень слота",
    )
    field.set_attributes_from_name(column_name)
    schema_editor.remove_field(WaiterSlot, field)


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0002_monthlyschedule_waiterslot_scheduleentry"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="waiterslot",
                    name="employee_level",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("employee_pro", "Опытный"),
                            ("employee_noob", "Стажёр"),
                        ],
                        db_index=True,
                        help_text=(
                            "Тип официанта из сгенерированного расписания "
                            "(employee_pro/employee_noob)"
                        ),
                        max_length=20,
                        null=True,
                        verbose_name="Уровень слота",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_employee_level_if_missing,
                    reverse_code=remove_employee_level_if_exists,
                )
            ],
        ),
    ]
