# Generated by Django 5.0.3 on 2026-03-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee_noob', 'Сотрудник (стажёр)'), ('employee_pro', 'Сотрудник (опытный)'), ('manager', 'Менеджер'), ('admin', 'Администратор')], db_index=True, default='employee_noob', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule_pattern',
            field=models.CharField(choices=[('4/3', '4 через 3'), ('4/2', '4 через 2'), ('3/2', '3 через 2'), ('2/2', '2 через 2')], default='4/2', max_length=10, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift_duration',
            field=models.CharField(choices=[('8h', '8 часов'), ('14h', '14 часов'), ('custom', 'По договорённости')], default='14h', help_text='Определяет допустимые типы смен для сотрудника', max_length=10, verbose_name='Продолжительность смены'),
        ),
    ]
