# Generated by Django 5.0.3 on 2026-04-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_migrate_employee_to_noob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedule_pattern',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shift_duration',
        ),
    ]
